### ISSUE TITLE
DB : fix db archi

### ISSUE THREAD

**Issue by LeBenjos** [openbox-dev/openbox-server#24]
fix la db suite au retour de Louisan

**Comment by LeBenjos** [comment]
@LTOssian Du coup j'ai fix la db suivant tes retours.
Pour les images je pense le mieux c'est d'avoir des images par défaut pour ça on a deux options : 
- On stock le chemin par défaut dans la db et il n'est remplacé que si on ajoute une nouvelle image.
- On ne stock pas le chemin par défaut dans la DB et quand on fetch si on ne récupère pas d'image on renvoie vers l'image par défaut.
Pour la table Box_follower :
- Je pas pense qu'on est hors scope perso

**Comment by LeBenjos** [comment]
Je ne fais pas de PR de suite j'attend ton ta review

**Comment by LTOssian** [comment]
Tout est ok @LeBenjos 
OK aussi pour le Box_Follower mais faut pas oublier l'idée qu'on peut tout suggérer, que ce soit une box, un event ou un intervenant
On garde la table comme telle mais dans ce cas il en manque quelques autres. On y réfléchis quand on se met sur le code de la page qui gère ça si tu veux bien

**Comment by LeBenjos** [comment]
Ce soir, je vais prendre le temps de réfléchir tranquillement à la base de données. Je vais vérifier s'il ne manque rien concernant la proposition de box, et également reconsidérer les deux types de box : les récurrentes et les occasionnelles.

**Comment by LeBenjos** [comment]
J'me note qu'il faut ajouter dans les rooms la possibilité d'être en visio (discord) donc rajouter un link d'invite vers le salon vocal (on peut avoir un event qui se déroule en **présentielle + redif sur twitch && || discord**)

**Comment by LeBenjos** [comment]
J'me note aussi la possibilité de faire des retour sur les event (le livre d'or)

**Comment by LeBenjos** [comment]
J'ai update la table Event, et ajouté des feedbacks. @LTOssian une autre idée ou je merge ?
